[2025-05-14 08:34:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:34:33] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:34:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:34:43] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:34:48] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:34:49] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-14 08:34:49] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'response' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\protocol\LSIS\client\tcp.py", line 83, in connect
    self.socket = socket.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python312\Lib\socket.py", line 865, in create_connection
    raise exceptions[0]
  File "C:\Python\Python312\Lib\socket.py", line 850, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 29, in tcp_client_servive
    connect_sock.connect(retry_forever=False)
  File "D:\project\projects\jais\py_backend\utils\protocol\LSIS\client\tcp.py", line 100, in connect
    raise ConnectionException(
utils.protocol.LSIS.exceptions.ConnectionException: LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 92, in tcp_client_servive
    values=response.values
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[2025-05-14 08:34:54] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:34:54] [ERROR] tcp_client_servive : LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004
[2025-05-14 08:34:54] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: cannot access local variable 'response' where it is not associated with a value
Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\protocol\LSIS\client\tcp.py", line 83, in connect
    self.socket = socket.create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python312\Lib\socket.py", line 865, in create_connection
    raise exceptions[0]
  File "C:\Python\Python312\Lib\socket.py", line 850, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 연결된 구성원으로부터 응답이 없어 연결하지 못했거나, 호스트로부터 응답이 없어 연결이 끊어졌습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 29, in tcp_client_servive
    connect_sock.connect(retry_forever=False)
  File "D:\project\projects\jais\py_backend\utils\protocol\LSIS\client\tcp.py", line 100, in connect
    raise ConnectionException(
utils.protocol.LSIS.exceptions.ConnectionException: LSIS_ Error: [Connection] Failed to connect to 192.168.0.198:2004

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 92, in tcp_client_servive
    values=response.values
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'response' where it is not associated with a value
[2025-05-14 08:35:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:36:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:36:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:39:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:43:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:46:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:47:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:48:53] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:48:53] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:48:53] [ERROR] tcp_client_servive : name 'kwargs' is not defined
[2025-05-14 08:48:58] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:48:58] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:48:58] [ERROR] tcp_client_servive : name 'kwargs' is not defined
[2025-05-14 08:49:03] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:03] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:03] [ERROR] tcp_client_servive : name 'kwargs' is not defined
[2025-05-14 08:49:08] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:08] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:08] [ERROR] tcp_client_servive : name 'kwargs' is not defined
[2025-05-14 08:49:18] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:18] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:18] [ERROR] tcp_client_servive : utils.protocol.LSIS.utilities.LSIS_MappingTool() argument after ** must be a mapping, not int
[2025-05-14 08:49:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:23] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:23] [ERROR] tcp_client_servive : utils.protocol.LSIS.utilities.LSIS_MappingTool() argument after ** must be a mapping, not int
[2025-05-14 08:49:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:28] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:28] [ERROR] tcp_client_servive : utils.protocol.LSIS.utilities.LSIS_MappingTool() argument after ** must be a mapping, not int
[2025-05-14 08:49:33] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:33] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:33] [ERROR] tcp_client_servive : utils.protocol.LSIS.utilities.LSIS_MappingTool() argument after ** must be a mapping, not int
[2025-05-14 08:49:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:38] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:38] [ERROR] tcp_client_servive : utils.protocol.LSIS.utilities.LSIS_MappingTool() argument after ** must be a mapping, not int
[2025-05-14 08:49:43] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:43] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:43] [ERROR] tcp_client_servive : utils.protocol.LSIS.utilities.LSIS_MappingTool() argument after ** must be a mapping, not int
[2025-05-14 08:49:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:49:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:49:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:22] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:27] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:27] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:32] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:37] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:50:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:50:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:01] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:51:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:51:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:01] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:52:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:52:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:01] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:14] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:14] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:19] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:24] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:29] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:34] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:34] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:39] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:44] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:49] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:54] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:54] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:54] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:53:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:53:59] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:04] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:09] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:09] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:14] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:14] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:19] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:24] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:29] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:34] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:34] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:39] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:44] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:49] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:54] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:54] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:54] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:54:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:54:59] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:04] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:09] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:09] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:14] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:14] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:22] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:27] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:27] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:32] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:37] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:42] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:42] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:42] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:47] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:52] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:52] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:55:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:57] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:55:57] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:02] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:02] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:07] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:12] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:17] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:17] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:24] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:29] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:37] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:42] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:42] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:42] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:47] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:52] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:52] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:56:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:56:59] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:04] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:09] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:09] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:19] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:24] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:29] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:34] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:34] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:39] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:44] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:49] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:54] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:54] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:54] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:57:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:57:59] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:04] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:09] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:09] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:14] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:14] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:19] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:24] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:34] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:34] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:39] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:44] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:49] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:58:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:58:59] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 08:59:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 08:59:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:07] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:12] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:17] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:17] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:22] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:28] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:28] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:33] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:33] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:33] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:39] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:43] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:43] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:43] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:00:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:00:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:01:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:01:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:01] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:02:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:02:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:01] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:03:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:03:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:01] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:04:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:04:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:32] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:37] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:42] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:42] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:42] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:47] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:06:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:52] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:06:52] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:02] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:02] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:07] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:44] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:49] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:07:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:57] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:07:57] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:02] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:02] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:07] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:12] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:17] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:17] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:22] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:32] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:37] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:42] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:42] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:42] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:47] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:52] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:52] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:08:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:57] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:08:57] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:09:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:09:02] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:09:02] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:09:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:09:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:09:07] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:09:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:09:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:09:12] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:20] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:25] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:30] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:30] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:35] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:35] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:45] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:45] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:10:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:10:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:20] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:25] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:30] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:30] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:35] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:35] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:45] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:45] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:11:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:11:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:12] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:17] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:17] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:22] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:27] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:27] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:32] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:12:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:12:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:06] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:11] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:16] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:16] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:16] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:21] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:26] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:31] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:36] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:41] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:46] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:51] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:13:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:13:56] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:14:03] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:03] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:03] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:08] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:08] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:08] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:13] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:13] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:13] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:18] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:18] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:18] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:23] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:23] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:28] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:28] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:33] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:33] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:33] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:38] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:38] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:47] [ERROR] tcp_client_servive : unsupported operand type(s) for *: 'int' and 'NoneType'
[2025-05-14 09:14:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:14:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:20] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:25] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:30] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:30] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:35] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:35] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:45] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:45] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:15:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:15:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:20] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:25] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:30] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:30] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:35] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:35] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:45] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:45] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:16:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:16:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:20] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:25] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:30] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:30] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:35] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:35] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:45] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:45] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:17:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:17:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:15] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:20] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:25] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:30] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:30] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:35] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:35] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:40] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:40] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:45] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:45] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:50] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:50] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:18:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:55] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:18:55] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:19:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:00] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:00] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:19:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:05] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:19:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:10] [ERROR] tcp_client_servive : 'LSIS_MappingTool' object has no attribute 'address_size'
[2025-05-14 09:19:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:20] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:29] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:34] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:34] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:39] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:44] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:49] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:54] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:54] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:54] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:19:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:19:59] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:20:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:20:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:20:04] [ERROR] tcp_client_servive : 'sys.int_info' object has no attribute 'min_int'
[2025-05-14 09:20:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:21] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:21] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:21] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:26] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:26] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:31] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:31] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:36] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:41] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:46] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:51] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:45:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:45:56] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:46:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:46:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:46:01] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:46:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:46:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:46:06] [ERROR] tcp_client_servive : 'int' object is not callable
[2025-05-14 09:46:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:46:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:47:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:55:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:59:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 09:59:48] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:12:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:13:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:15:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:17:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:18:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:18:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:19:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:19:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:20:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:21:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:49] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:22:54] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:54] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:54] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:22:59] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:59] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:22:59] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:04] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:09] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:09] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:14] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:14] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:19] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:24] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:29] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:34] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:34] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:39] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:39] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:44] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:44] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:44] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:49] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:49] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:23:58] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:58] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:23:58] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:04] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:04] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:09] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:09] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:14] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:14] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:19] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:24] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:29] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:29] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:24:29] [ERROR] tcp_client_servive : 'project_id'
[2025-05-14 10:24:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:22] [ERROR] tcp_client_servive : 'list' object has no attribute 'length'
[2025-05-14 10:27:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:27] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:27] [ERROR] tcp_client_servive : 'list' object has no attribute 'length'
[2025-05-14 10:27:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:32] [ERROR] tcp_client_servive : 'list' object has no attribute 'length'
[2025-05-14 10:27:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:27:37] [ERROR] tcp_client_servive : 'list' object has no attribute 'length'
[2025-05-14 10:27:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:28:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:28:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:28:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:28:58] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:29:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:29:48] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:30:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:32:26] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:32:53] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:33:14] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:33:38] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:34:00] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:34:09] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:35:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:35:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:37:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:38:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:39:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:40:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:40:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:41:49] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:42:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:45:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 10:46:18] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:05] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:05] [ERROR] tcp_client_servive : 'group_id'
[2025-05-14 11:16:10] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:10] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:10] [ERROR] tcp_client_servive : 'group_id'
[2025-05-14 11:16:15] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:15] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:15] [ERROR] tcp_client_servive : 'group_id'
[2025-05-14 11:16:20] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:20] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:20] [ERROR] tcp_client_servive : 'group_id'
[2025-05-14 11:16:25] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:25] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:25] [ERROR] tcp_client_servive : 'group_id'
[2025-05-14 11:16:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:16:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:19:39] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:40:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 11:43:58] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:21:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:22:34] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:25:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:26:55] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:27:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:27:08] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:28:31] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:29:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:29:53] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:31:30] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:33:40] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:34:03] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:34:45] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:35:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:35:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:42:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:43:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:47:54] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:48:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:48:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:50:04] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:50:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:50:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:51:13] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:51:50] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:08] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:08] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:08] [ERROR] tcp_client_servive : SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:08] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: SocketClientStatus has no field named 'update_at'
Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 71, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 96, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:13] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:13] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:13] [ERROR] tcp_client_servive : SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:13] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: SocketClientStatus has no field named 'update_at'
Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 71, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 96, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:18] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:18] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:18] [ERROR] tcp_client_servive : SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:18] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: SocketClientStatus has no field named 'update_at'
Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 71, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 96, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:23] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:23] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:23] [ERROR] tcp_client_servive : SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:23] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: SocketClientStatus has no field named 'update_at'
Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 71, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 96, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:28] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:28] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:52:28] [ERROR] tcp_client_servive : SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:28] [ERROR] 🚨 [ERROR] tcp_client_servive()에서 예외 발생 🚨
📌 파일: D:\project\projects\jais\py_backend\utils\logger.py, 라인: 67
📍 오류 메시지: SocketClientStatus has no field named 'update_at'
Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 71, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'update_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\projects\jais\py_backend\utils\logger.py", line 67, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project/projects/jais/py_backend\LSISsocket\service.py", line 96, in tcp_client_servive
    ).update(
      ^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\query.py", line 1233, in update
    query.add_update_values(kwargs)
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\sql\subqueries.py", line 88, in add_update_values
    field = self.get_meta().get_field(name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\projects\jais\pyvenv\Lib\site-packages\django\db\models\options.py", line 685, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: SocketClientStatus has no field named 'update_at'
[2025-05-14 12:52:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:53:18] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 12:53:35] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:32] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:07:42] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:42] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:42] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:07:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:47] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:07:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:52] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:52] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:07:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:57] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:07:57] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:02] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:02] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:07] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:12] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:17] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:17] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:17] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:22] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:22] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:22] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:27] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:27] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:27] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:32] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:37] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:42] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:42] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:42] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:47] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:47] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:52] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:52] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:52] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:08:57] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:57] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:08:57] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:02] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:02] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:02] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:07] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:07] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:07] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:12] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:12] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:12] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:36] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:36] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:36] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:41] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:41] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:41] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:46] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:46] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:46] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:51] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:51] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:09:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:09:56] [ERROR] tcp_client_servive : 'dict' object has no attribute 'append'
[2025-05-14 13:10:05] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:10:51] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:13:56] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:13:56] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:13:56] [ERROR] tcp_client_servive : list assignment index out of range
[2025-05-14 13:14:01] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:01] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:01] [ERROR] tcp_client_servive : list assignment index out of range
[2025-05-14 13:14:06] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:06] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:06] [ERROR] tcp_client_servive : list assignment index out of range
[2025-05-14 13:14:11] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:11] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:11] [ERROR] tcp_client_servive : list assignment index out of range
[2025-05-14 13:14:19] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:19] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:19] [ERROR] tcp_client_servive : 'list' object has no attribute 'appned'
[2025-05-14 13:14:24] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:24] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:24] [ERROR] tcp_client_servive : 'list' object has no attribute 'appned'
[2025-05-14 13:14:32] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:32] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:32] [ERROR] tcp_client_servive : 'list' object has no attribute 'appned'
[2025-05-14 13:14:37] [INFO] try to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:37] [ERROR] cancel to connect LSIS client => 192.168.0.198:2004
[2025-05-14 13:14:37] [ERROR] tcp_client_servive : 'list' object has no attribute 'appned'
[2025-05-14 13:14:47] [INFO] try to connect LSIS client => 192.168.0.198:2004
